Generic history for different sensors
jakkra/ZSWatch pull request #263
Opened 2024-04-22 13:26 UTC by Kampi

First idea and not tested.

2024-05-03 16:48 UTC, jakkra approved these changes
Looks awesome!

2024-05-03 20:25 UTC, Kampi commented
> Looks awesome!

But doesn´t work yet :D

2024-05-22 07:46 UTC, jakkra requested changes

2024-05-22 07:46 UTC, jakkra commented on app/src/history/zsw_history.c
> +    error = settings_delete(key_header);
Don't understand why there is a delete here, do you know why?
Edit: I see it was in the battery app before, but I think that's wrong?

2024-05-22 07:46 UTC, jakkra commented on app/src/history/zsw_history.c
> +void zsw_history_add(zsw_history_t *p_history, const void *p_sample)
Should we make this static instead? It's right now only used inside this file.

2024-05-22 07:46 UTC, jakkra commented on app/src/history/zsw_history.c
> +void zsw_history_add(zsw_history_t *p_history, const void *p_sample)
I suggest renaming `zsw_history_save` to `zsw_history_add`, as that's the one actually doing the adding and saving of a new sample. Think it makes it a bit more clear when used.

2024-05-22 07:46 UTC, jakkra commented on app/src/history/zsw_history.c
> +void zsw_history_del(zsw_history_t *p_history)
Should `zsw_history_del` also delete the settings? Otherwise let's say you call `zsw_history_del` and then reset the watch before a new sample was added, then next time watch boots, it will read in the old samples.

2024-05-22 07:46 UTC, jakkra commented on app/src/history/zsw_history.c
> +    error = settings_load_subtree_direct(key_header, zsw_history_load_header_cb, p_history);
For me `zsw_history_load_header_cb` never gets called, and even with an erased flash it says max samples stored.

2024-05-22 07:46 UTC, jakkra commented on app/src/history/zsw_history.c
> +    error = settings_load_subtree_direct(key_data, zsw_history_load_data_cb, p_history);
Same, `zsw_history_load_data_cb` not called for me

2024-05-22 07:50 UTC, jakkra commented on app/src/applications/battery/battery_app.c
>      if (settings_delete(SETTING_BATTERY_HIST) != 0) {
Move this delete into `zsw_history_del`

2024-05-22 08:32 UTC, Kampi commented on app/src/history/zsw_history.c
> +    error = settings_delete(key_header);
It depends if you want to keep the history after loading it.

2024-05-22 08:34 UTC, Kampi commented on app/src/history/zsw_history.c
> +void zsw_history_add(zsw_history_t *p_history, const void *p_sample)
The idea was to use `zsw_history_add` for adding a sample to a history without saving the history on the file system. `zsw_history_save` can be used for storing it also on the file system.

2024-05-22 08:35 UTC, jakkra commented on app/src/history/zsw_history.c
> +    error = settings_delete(key_header);
Think you always want. Don't see why not. Also you may run into issues when you load and then reset the watch before a save has been done. Then all data will be lost.

2024-05-22 08:35 UTC, Kampi commented on app/src/history/zsw_history.c
> +void zsw_history_del(zsw_history_t *p_history)
Good point.

2024-05-22 08:38 UTC, jakkra commented on app/src/history/zsw_history.c
> +    error = settings_load_subtree_direct(key_data, zsw_history_load_data_cb, p_history);
My bad, working

2024-05-22 08:38 UTC, jakkra commented on app/src/history/zsw_history.c
> +    error = settings_load_subtree_direct(key_header, zsw_history_load_header_cb, p_history);
My bad, working

2024-05-22 08:41 UTC, jakkra commented on app/src/history/zsw_history.c
> +void zsw_history_add(zsw_history_t *p_history, const void *p_sample)
Ok, I see, good. Could update save to not take any arg and require the user to first add and then call save?
I see uses for add and the one save when done. For example when sampling alot of data, you sample and when done you call save. OR maybe allow input NULL to `zsw_history_save` to just make a save without adding, maybe the most flexible way!

2024-05-22 08:43 UTC, jakkra commented
I think we should include num_stored_samples in the `zsw_history_t` to allow the user to know how many of the samples are actually valid. Since the `num` param today is always the max number of samples. Or can `num` be changed to actually reflect the number of valid samples?

2024-05-22 08:46 UTC, jakkra commented
> I think we should include num_stored_samples in the `zsw_history_t` to allow the user to know how many of the samples are actually valid. Since the `num` param today is always the max number of samples. Or can `num` be changed to actually reflect the number of valid samples?

Because in the battery app now it plots all samples, which are all 0 so it's hard to see anything.

2024-05-22 10:26 UTC, Kampi commented on app/src/history/zsw_history.c
> +    error = settings_delete(key_header);
Okay so I remove it.

2024-05-22 10:28 UTC, Kampi commented on app/src/history/zsw_history.c
> +void zsw_history_add(zsw_history_t *p_history, const void *p_sample)
Or maybe split "add" and "save"? So you use "add" for adding values to the history and then you can call save to save the history but save doesn´t add a value to the history. I think this is the more intuitive way?

2024-05-22 10:29 UTC, Kampi commented on app/src/history/zsw_history.c
> +    error = settings_delete(key_header);
You can call `zsw_history_del` after loading it if you don´t want to keep it.

2024-05-22 10:31 UTC, Kampi commented
> > I think we should include num_stored_samples in the `zsw_history_t` to allow the user to know how many of the samples are actually valid. Since the `num` param today is always the max number of samples. Or can `num` be changed to actually reflect the number of valid samples?
> 
> Because in the battery app now it plots all samples, which are all 0 so it's hard to see anything.

I think we should keep `num` as an indicator for the maximum size of the buffer. But sure we can add a counter for the added samples.

2024-05-22 10:33 UTC, Kampi commented
> > I think we should include num_stored_samples in the `zsw_history_t` to allow the user to know how many of the samples are actually valid. Since the `num` param today is always the max number of samples. Or can `num` be changed to actually reflect the number of valid samples?
> 
> Because in the battery app now it plots all samples, which are all 0 so it's hard to see anything.

I think we should keep `num` (but rename it to length) to have an indicator about the maximum length. Then we add a sample counter.

2024-05-22 10:37 UTC, jakkra commented
> > > I think we should include num_stored_samples in the `zsw_history_t` to allow the user to know how many of the samples are actually valid. Since the `num` param today is always the max number of samples. Or can `num` be changed to actually reflect the number of valid samples?
> > 
> > 
> > Because in the battery app now it plots all samples, which are all 0 so it's hard to see anything.
> 
> I think we should keep `num` (but rename it to length) to have an indicator about the maximum length. Then we add a sample counter. Or we can use `write_index` for it?

Sounds good, or even max_samples or sample_buffer_size so it's clear it's a different length

2024-05-22 10:55 UTC, Kampi commented on app/src/history/zsw_history.c
> +    error = settings_delete(key_header);
Okay so Ieave it as it is.

2024-05-22 11:04 UTC, jakkra commented on app/src/history/zsw_history.c
> +    error = settings_delete(key_header);
> Okay so Ieave it as it is.

No remove

2024-05-23 09:20 UTC, jakkra requested changes

2024-05-23 09:20 UTC, jakkra commented on app/src/history/zsw_history.c
> +    return p_history->write_index;
Will not work, when max samples are used, the write_index will wrap around to 0 again.
Need to add another variable into the setting struct. Adding that.

2024-05-23 09:20 UTC, jakkra commented on app/src/history/zsw_history.c
> +int zsw_history_save(zsw_history_t *p_history, const void *p_sample)
p_sample unused, causing battery_app not to add any samples. I'm fixing this by adding the sample if p_sample != NULL

2024-05-23 09:34 UTC, Kampi commented on app/src/history/zsw_history.c
> +int zsw_history_save(zsw_history_t *p_history, const void *p_sample)
No - `zsw_history_save` should only save the history to NVS without adding a sample. I just forgot to remove this parameter yesterday.

2024-05-23 09:35 UTC, Kampi commented on app/src/history/zsw_history.c
> +int zsw_history_save(zsw_history_t *p_history, const void *p_sample)
The workflow should be to use `zsw_history_add` to add the samples to the history and then call `zsw_history_save` when you are done and when you want to save it.

2024-05-26 06:31 UTC, jakkra commented
Ok, it's my voltage compressions int mV => byte which is bad, nothing wrong with history code I think.

2024-05-27 20:26 UTC, jakkra approved these changes
Done and I think it works.

2024-05-27 20:26 UTC, merged