Rework popup notification
jakkra/ZSWatch pull request #37
Opened 2023-08-15 17:48 UTC by AlmazShai

Reworked notification UI to make full message visible on screen. Notification message size now is limited to 3 lines of message, but the user can expand the message by clicking on it. Clicking on expanded message one more time will remove the message.

I like to replace "Bell" symbol with small application symbol in future, but I would like to take I look to notification manages to be able to understand if it's possible to show sender name instead of application name.

2023-08-15 17:52 UTC, AlmazShai commented
Short form of notification message now looks like:
![photo_2023-08-15_20-45-38](https://github.com/jakkra/ZSWatch/assets/34490376/2a860066-e070-4f04-8bfd-f2a808477e6c)

2023-08-15 21:20 UTC, jakkra requested changes
Tested and works like a charm! Just some minor things.

2023-08-15 21:20 UTC, jakkra commented on app/src/ui/zsw_popup_notifcation.c
> +    lv_label_set_text(notif_box.title, title_text);
You can use `lv_label_set_text_fmt(notif_box.title, "%s %s", LV_SYMBOL_BELL, title);` and skip the `title_text` and strcpy lines above. `lv_label_set_text_fmt` is a very handy function.

2023-08-15 21:20 UTC, jakkra commented on app/src/ui/zsw_popup_notifcation.c
> +    // TODO: replace with application symbol
I think we can do it this way later in order to easily add some more notification icons. https://docs.lvgl.io/8.3/overview/font.html#add-new-symbols Those will also tacke much less flash than the icons I have today.

2023-08-15 21:20 UTC, jakkra commented on app/src/ui/zsw_popup_notifcation.c
>  LV_IMG_DECLARE(notification);
You can remove those and also delete the .c files in images folder.

2023-08-16 12:59 UTC, AlmazShai commented on app/src/ui/zsw_popup_notifcation.c
> +    lv_label_set_text(notif_box.title, title_text);
Fixed in last commit

2023-08-16 16:29 UTC, merged